# Generated by Django 5.0.6 on 2024-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/uploads/category/téléchargement (1).jpg', upload_to='uploads/category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_coming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_exclusif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
